### ISSUE TITLE
Styling the button component

### ISSUE THREAD

**Issue by aelamel** [aelamel/react-bs#11]

**Comment by manikaaggarwal** [comment]
Can you provide more info on how to style.

**Comment by aelamel** [comment]
Any fancy style is appreciated, bootstrap is integrated into to project for inspiration.

**Comment by muhammadawaisshaikh** [comment]
can I pick this ticket?

**Comment by karans5004** [comment]
@aelamel : Raised a PR #21 for same. Pl review and let me know if any changes required.
