### ISSUE TITLE
Adding a checkbox component

### ISSUE THREAD

**Issue by aelamel** [aelamel/react-bs#18]
The checkbox should have the following props : 

**checked**: For checking or unchecking 
**disabled**: For enabling or disabling the component
**label**: A text display next to the checkbox (Text in the left side)
**onCheck**: a handler that intercepts the check event.

**Comment by rasfa98** [comment]
Hi @aelamel 🙂 Can I fix this?

**Comment by rasfa98** [comment]
> Hi @aelamel 🙂 Can I fix this?

Fixed in #19 🙂

**Comment by aelamel** [comment]
@rasfa98 Thanks.
