### ISSUE TITLE
Integrating storybook

### ISSUE THREAD

**Issue by aelamel** [aelamel/react-bs#7]

**Comment by manikaaggarwal** [comment]
I can work.

**Comment by ThaGeek** [comment]
Go ahead

**Comment by aelamel** [comment]
Go ahead !

**Comment by manikaaggarwal** [comment]
I have integrated the storybook and it appears like this 
<img width="1615" alt="image" src="https://user-images.githubusercontent.com/16543609/94992600-cbfe0900-05a8-11eb-97da-6c0ad0050fa9.png">

**Comment by manikaaggarwal** [comment]
Do you want me to include yarn.lock file in the commit?

**Comment by aelamel** [comment]
@manikaaggarwal That look great, can you please remove the generated stories and only leave the story for the library button (located in `components/Button`)

Include the yarn.lock file in your pull request.

Thanks.

**Comment by manikaaggarwal** [comment]
Okay I have removed rest of the stories except button. 
I also added this in web pack config, because css file loader wasn't there, 
<img width="494" alt="image" src="https://user-images.githubusercontent.com/16543609/94992851-598e2880-05aa-11eb-86b8-b00da403be4f.png">
Shall I commit same?

**Comment by aelamel** [comment]
The webpack config is fixed in #10, you can rebase so you get the fix locally.

**Comment by manikaaggarwal** [comment]
Hey @aelamel , since it was my first time with storybook integration , I didn't notice the buttons were not the project buttons.
Those were the default buttons. I am submitting another PR, which renders the button in the component folder.
